SPRING_DATASOURCE_URL=jdbc:mysql://switchyard.proxy.rlwy.net:49002/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
SPRING_DATASOURCE_USERNAME=root
SPRING_DATASOURCE_PASSWORD=<Railway ka naya password>
JWT_SECRET=<apna base64 secret>
